version: "3"
services:
  web:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:secret@db:5432/rails_api_boiler_plate_development
      YARN_INTEGRITY_ENABLED: "false"
    volumes:
      - .:/usr/src/app
    command: bundle exec rails s -b 0.0.0.0 -p 3000
  db:
    image: postgres:10.5-alpine
    ports:
    - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rails_api_boiler_plate_development
  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:8080"
    environment:
      ADMINER_PLUGINS: "dump-json"
volumes:
  dbdata: